### ISSUE TITLE
Linux Release?

### ISSUE THREAD

**Issue by abdulAttya** [MustaphaTR/Generals-Alpha#20]
why there is a windows release but not linux

**Comment by MustaphaTR** [comment]
There was some issues with the packaging scripts, rather than trying to fix the issue specifically, i went ahead and done another engine update, this time, finally, to latest version of OpenRA engine. It'll take a while till i can get that version released. For the time being, you can play the previous release (gen-20230424), if you wanna play on Linux (i wouldn't recommend manually building current dev version, while it runs, there are stuff missing that i need to add back). I haven't actually posted gen-20230705 on Discord or ModDB, it is just here.

**Comment by abdulAttya** [comment]
cool
